/**
 * Canonical Pawning privilege Description strings (user_privilages.Description).
 * Exact match is required — keep in sync with Account Center DB.
 *
 * Intentionally excluded (do not gate with these):
 * - PAWNING TICKET DISBURSE (Account Center handles disbursement)
 * - TICKET PAYMENT UNDONE
 * - PAWNING TICKET MAX APPROVE AMOUNT
 */
export const PAWNING_PRIVILEGES = {
  CUSTOMER_CREATE: "CUSTOMER CREATE",
  CUSTOMER_UPDATE: "CUSTOMER UPDATE",
  CUSTOMER_VIEW: "CUSTOMER VIEW",
  KYC_ACCESS: "KYC ACCESS (KNOW YOUR CUSTOMER)",

  PRODUCT_CREATE: "PAWNING PRODUCT CREATE",
  PRODUCT_UPDATE: "PAWNING PRODUCT UPDATE",
  PRODUCT_VIEW: "PAWNING PRODUCT VIEW",

  TICKET_CREATE: "PAWNING TICKET CREATE",
  TICKET_VIEW: "PAWNING TICKET VIEW",
  TICKET_PRINT: "PAWNING TICKET PRINT",
  TICKET_DOWNLOAD: "PAWNING TICKET DOWNLOAD",
  TICKET_LOG_VIEW: "PAWNING TICKET LOG VIEW",
  TICKET_DUPLICATE_PRINT: "PAWNING TICKET DUPLICATE PRINT",
  TICKET_RENEWAL: "PAWNING TICKET RENEWAL",
  TICKET_APPROVE: "PAWNING TICKET APPROVE",
  TICKET_REJECT: "PAWNING TICKET REJECT",
  TICKET_SETTLEMENT: "PAWNING TICKET SETTLEMENT",

  TICKET_PAYMENT: "PAWNING TICKET PAYMENT",
  TICKET_PAYMENT_HISTORY_VIEW: "PAWNING TICKET PAYMENT HISTORY VIEW",
  TICKET_PAYMENT_PRINT: "PAWNING TICKET PAYMENT PRINT",
  PAYMENTS_HISTORY_VIEW: "PAYMENTS HISTORY VIEW",
  PAYMENT_HISTORY_PRINT: "PAYMENT HISTORY PRINT",

  REPORTS: "REPORTS",
};
